set -g prefix C-g
unbind C-b
bind C-g send-prefix;

# prefix+\でペインを垂直分割する
bind \\ split-window -h

# prefix+-でペインを水平分割する
bind - split-window -v

# prefix + q の表示時間を伸ばす
set -g display-panes-time 3000

setw -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle
bind-key -T copy-mode-vi 'y' send -X copy-selection 
 
set -s escape-time 0

